name: Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekcout@v3
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        width:
          node-version: "20"
      - run: npm install
      - run: npm run build --prefix client
